# Generated by Django 4.2 on 2026-01-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Ej: Dr., Dra., Mag., Abg.', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripcion breve para mostrar en el sidebar')),
                ('firma', models.CharField(blank=True, help_text='Firma estilizada, ej: Camilo Soler R.', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autor/')),
            ],
            options={
                'verbose_name': 'Perfil del Autor',
                'verbose_name_plural': 'Perfil del Autor',
            },
        ),
    ]
