# Generated by Django 4.2 on 2026-01-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoColumna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Archivo de columna',
                'verbose_name_plural': 'Archivo de columnas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('subtitulo', models.CharField(blank=True, help_text='Lead o bajada del artículo', max_length=500)),
                ('contenido', models.TextField()),
                ('extracto', models.TextField(blank=True, help_text='Resumen para listados y SEO', max_length=500)),
                ('imagen_destacada', models.ImageField(blank=True, null=True, upload_to='articulos/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL externa de imagen (alternativa)')),
                ('pie_imagen', models.CharField(blank=True, max_length=200)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tiempo_lectura', models.PositiveIntegerField(default=5, help_text='Minutos estimados de lectura')),
                ('vistas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar en posición destacada')),
                ('meta_descripcion', models.CharField(blank=True, help_text='Descripción para SEO', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por coma', max_length=200)),
                ('og_image', models.URLField(blank=True, help_text='Imagen para compartir en redes sociales')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-fecha_publicacion', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('titulo', models.CharField(blank=True, help_text='Ej: Dr., Dra., Mag.', max_length=100)),
                ('cargo', models.CharField(blank=True, help_text='Ej: Abogado constitucionalista', max_length=200)),
                ('biografia', models.TextField(blank=True)),
                ('biografia_corta', models.CharField(blank=True, help_text='Descripción breve para sidebar', max_length=300)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='autores/')),
                ('firma', models.CharField(blank=True, help_text='Firma estilizada, ej: Camilo Soler R.', max_length=100)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_principal', models.BooleanField(default=False, help_text='Autor principal del sitio')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CapsulaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cápsula jurídica',
                'verbose_name_plural': 'Cápsulas jurídicas',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Camilo Andres Soler Rueda', max_length=200)),
                ('subtitulo', models.CharField(default='Derecho - Politica - Pensamiento Critico', max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('ticker_texto', models.CharField(default='Estado de Derecho * Constitucionalismo * Analisis Politico * Opinion Juridica', max_length=500)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('ubicacion', models.CharField(blank=True, default='Bogota, Colombia', max_length=200)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('token_confirmacion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-fecha_suscripcion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(blank=True, help_text='Cargo / Institución', max_length=200)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('votos_utiles', models.PositiveIntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('es_autor', models.BooleanField(default=False, help_text='Comentario del autor del artículo')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='main.articulo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='main.comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CitaDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor_cita', models.CharField(blank=True, help_text='Autor de la cita si no es el autor del artículo', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='main.articulo')),
            ],
            options={
                'verbose_name': 'Cita destacada',
                'verbose_name_plural': 'Citas destacadas',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='main.autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='main.categoria'),
        ),
    ]
