# Generated by Django 4.2 on 2026-01-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilautor',
            name='titulo',
            field=models.CharField(blank=True, help_text='Ej: Dr., Dra., Mag., Abg.', max_length=180),
        ),
    ]
