# Generated by Django 4.2 on 2026-01-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_perfilautor_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsulaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(help_text='Contenido breve de la capsula', max_length=500)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor numero aparece primero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Capsula Juridica',
                'verbose_name_plural': 'Capsulas Juridicas',
                'ordering': ['orden', '-pk'],
            },
        ),
    ]
