# Generated by Django 4.2 on 2026-01-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categoria_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='extracto',
            field=models.TextField(blank=True, help_text='Resumen breve para listados y SEO', max_length=500),
        ),
    ]
