# Generated by Django 4.2 on 2026-01-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_articulo_extracto'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL externa de imagen (alternativa a subir archivo)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='meta_descripcion',
            field=models.CharField(blank=True, help_text='Descripcion para motores de busqueda', max_length=160),
        ),
        migrations.AddField(
            model_name='articulo',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Palabras clave separadas por coma', max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='og_image',
            field=models.URLField(blank=True, help_text='URL de imagen para redes sociales'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='pie_imagen',
            field=models.CharField(blank=True, help_text='Descripcion o creditos de la imagen', max_length=200),
        ),
    ]
