# Generated by Django 4.2 on 2026-01-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articulo_imagen_url_articulo_meta_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre visible de la red social, ej: YouTube / Podcast', max_length=100)),
                ('descripcion', models.CharField(help_text='Descripcion breve del contenido en esta red', max_length=200)),
                ('url', models.URLField(help_text='Enlace al perfil o canal', max_length=500)),
                ('icono', models.CharField(choices=[('bi-twitter-x', 'X (Twitter)'), ('bi-linkedin', 'LinkedIn'), ('bi-youtube', 'YouTube'), ('bi-instagram', 'Instagram'), ('bi-facebook', 'Facebook'), ('bi-tiktok', 'TikTok'), ('bi-spotify', 'Spotify'), ('bi-envelope', 'Email'), ('bi-globe', 'Sitio Web')], help_text='Icono de Bootstrap Icons', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor numero aparece primero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
