# Generated by Django 4.2 on 2026-01-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_redsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilautor',
            name='bio_footer',
            field=models.TextField(blank=True, help_text='Descripcion breve para el footer (primer parrafo)'),
        ),
        migrations.AddField(
            model_name='perfilautor',
            name='bio_footer_2',
            field=models.TextField(blank=True, help_text='Descripcion adicional para el footer (segundo parrafo)'),
        ),
    ]
