# Generated by Django 4.2 on 2026-02-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_perfilautor_bio_footer_perfilautor_bio_footer_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Ej: Estado de Derecho, Constitucionalismo', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Menor numero aparece primero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Tickers',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
