# Generated by Django 4.2 on 2026-02-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tickeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(help_text='Texto superior pequeno, ej: Circulo Editorial Privado', max_length=100)),
                ('titulo', models.CharField(help_text='Titulo principal, ej: Boletin de Analisis Juridico y Politico', max_length=200)),
                ('descripcion', models.TextField(help_text='Texto descriptivo debajo del titulo')),
                ('nota', models.CharField(blank=True, help_text='Nota al pie del formulario', max_length=200)),
            ],
            options={
                'verbose_name': 'Seccion de Suscripcion',
                'verbose_name_plural': 'Seccion de Suscripcion',
            },
        ),
    ]
